/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    // Initialize and declare all variables, constants, and arrays
    int randomAnimal = 0;
    int correctGuess = 0;
    double percCorrect = 0;
    int incorrectGuess = 0;
    int guessNumber = 0;
    int total = 0;
    int rollAmount = 0;
    String Guess;

    final String GIRAFFE = "Yellow and brown, long neck, what am I?";
    final String ELEPHANT = "Big ears and nose, what am I?";
    final String DOG = "Usually furry and need attention, what am I?";
    final String CAT = "Will knock over anything on a table, what am I?";
    final String ZEBRA = "I am black and white, what am I?";
    String[] animals = {GIRAFFE, ELEPHANT, DOG, CAT, ZEBRA};

    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGuess = new javax.swing.JTextField();
        BtnCheck = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        lblInstructionsPt1 = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        lblInstructionsPt2 = new javax.swing.JLabel();
        BtnRandomAnimal = new javax.swing.JButton();
        lblHint = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblGuess = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblInstructionsPt3 = new javax.swing.JLabel();
        txtRollAmount = new javax.swing.JTextField();
        lblRollTimesInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGuess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGuess.setToolTipText("");
        txtGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuessActionPerformed(evt);
            }
        });

        BtnCheck.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnCheck.setForeground(new java.awt.Color(255, 51, 51));
        BtnCheck.setText("Check");
        BtnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCheckActionPerformed(evt);
            }
        });

        lblOutput.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(0, 0, 0));
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblInstructionsPt1.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblInstructionsPt1.setForeground(new java.awt.Color(0, 0, 0));
        lblInstructionsPt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructionsPt1.setText("Click the button below, enter your guess for the animal, and click check!");

        lblPercentValue.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblPercentValue.setForeground(new java.awt.Color(153, 0, 0));
        lblPercentValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPercentValue.setText("0");

        lblInstructionsPt2.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblInstructionsPt2.setForeground(new java.awt.Color(0, 0, 0));
        lblInstructionsPt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructionsPt2.setText("Enter your guess for the animal and click check!");

        BtnRandomAnimal.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnRandomAnimal.setForeground(new java.awt.Color(255, 51, 51));
        BtnRandomAnimal.setText("New Random Animal");
        BtnRandomAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRandomAnimalActionPerformed(evt);
            }
        });

        lblHint.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lblHint.setForeground(new java.awt.Color(0, 0, 0));
        lblHint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCorrect.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(0, 153, 255));
        lblCorrect.setText("Number Of Correct Guesses:");

        lblPercent.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblPercent.setForeground(new java.awt.Color(0, 153, 255));
        lblPercent.setText("Percentage Of Correct Guesses:");

        lblGuess.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblGuess.setForeground(new java.awt.Color(0, 153, 255));
        lblGuess.setText("Guess:");

        lblCorrectValue.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblCorrectValue.setForeground(new java.awt.Color(153, 0, 0));
        lblCorrectValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorrectValue.setText("0");

        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Guess that Animal!");

        lblIncorrect.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblIncorrect.setForeground(new java.awt.Color(0, 153, 255));
        lblIncorrect.setText("Number Of Incorrect Guesses:");

        lblIncorrectValue.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblIncorrectValue.setForeground(new java.awt.Color(153, 0, 0));
        lblIncorrectValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncorrectValue.setText("0");

        lblInstructionsPt3.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblInstructionsPt3.setForeground(new java.awt.Color(0, 0, 0));
        lblInstructionsPt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructionsPt3.setText("How many times do you wish to roll the animal dice before having to guess?");

        txtRollAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRollAmount.setText("1");
        txtRollAmount.setToolTipText("");
        txtRollAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRollAmountActionPerformed(evt);
            }
        });

        lblRollTimesInfo.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblRollTimesInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblRollTimesInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRollTimesInfo.setText("You will roll 1 time(s) before being asked the question.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRollAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnRandomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblGuess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInstructionsPt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInstructionsPt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInstructionsPt3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRollTimesInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(BtnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPercent)
                                    .addComponent(lblCorrect)
                                    .addComponent(lblIncorrect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCorrectValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPercentValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructionsPt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRollAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblRollTimesInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstructionsPt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRandomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHint, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructionsPt2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrect)
                    .addComponent(lblCorrectValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercent)
                    .addComponent(lblPercentValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncorrect)
                    .addComponent(lblIncorrectValue))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuessActionPerformed

    private void BtnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCheckActionPerformed

        //Get users animal guess
        Guess = txtGuess.getText();

        // set the guess number to compare to based on the user input
        switch (Guess) {
            case "giraffe":
            case "Giraffe":
                guessNumber = 1;
                break;
            case "elephant":
            case "Elephant":
                guessNumber = 2;
                break;
            case "dog":
            case "Dog":
                guessNumber = 3;
                break;
            case "cat":
            case "Cat":
                guessNumber = 4;
                break;
            case "zebra":
            case "Zebra":
                guessNumber = 5;
                break;
            default:
                break;
        }
        // Depending if the guess number is equal to what the random animal is, it will add to correct and add to incorrect
        // If correct, it will generate another random animal
        if (guessNumber == randomAnimal) {
            lblOutput.setText("Your guess was correct!");
            correctGuess = correctGuess + 1;
            randomAnimalGenerator();
        } else {
            lblOutput.setText("Your guess was incorrect. Try again!");
            incorrectGuess = incorrectGuess + 1;
        }

        // Calculate the total
        total = correctGuess + incorrectGuess;

        // Calculate the percent correct
        percCorrect = ((double) correctGuess / (double) total) * 100;
        // Rounds the percent of correct guesses
        percCorrect = (double) Math.round(percCorrect * 100) / 100;

        // Output the values
        lblCorrectValue.setText(String.valueOf(correctGuess));
        lblIncorrectValue.setText(String.valueOf(incorrectGuess));
        lblPercentValue.setText(String.valueOf(percCorrect));
    }//GEN-LAST:event_BtnCheckActionPerformed

    // Function the generates a random animal
    public void randomAnimalGenerator() {
        // Gets how many times the user wants to randomize the animals and rolls it in a for loop that many times
        rollAmount = Integer.parseInt(txtRollAmount.getText());
        lblRollTimesInfo.setText("You will roll " + String.valueOf(rollAmount) + " time(s) before being asked the question.");
        for (int i = 0; i < rollAmount; i = i + 1) {
            randomAnimal = (int) Math.round(Math.random() * 4 + 1);
        }

        // Depending on what is rolled, it outputs the hint to the user
        lblHint.setText(animals[randomAnimal - 1]);
    }

    private void BtnRandomAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRandomAnimalActionPerformed

        // Calls the random animal generator function
        randomAnimalGenerator();
    }//GEN-LAST:event_BtnRandomAnimalActionPerformed

    private void txtRollAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRollAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCheck;
    private javax.swing.JButton BtnRandomAnimal;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblGuess;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblInstructionsPt1;
    private javax.swing.JLabel lblInstructionsPt2;
    private javax.swing.JLabel lblInstructionsPt3;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollTimesInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtGuess;
    private javax.swing.JTextField txtRollAmount;
    // End of variables declaration//GEN-END:variables
}
