/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVeggie = new javax.swing.JTextField();
        lblVeggie = new javax.swing.JLabel();
        BtnCalculateCost = new javax.swing.JButton();
        txtPepperoni = new javax.swing.JTextField();
        lblPepperoni = new javax.swing.JLabel();
        txtCheese = new javax.swing.JTextField();
        lblCheese = new javax.swing.JLabel();
        txtPineapple = new javax.swing.JTextField();
        lblPineapple = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        picPizza = new javax.swing.JLabel();
        Welcome1 = new javax.swing.JLabel();
        Welcome2 = new javax.swing.JLabel();
        lblMeat = new javax.swing.JLabel();
        txtMeat = new javax.swing.JTextField();
        lblOutput = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalOut = new javax.swing.JLabel();
        lblSubtotalOut = new javax.swing.JLabel();
        lblTaxesOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtVeggie.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtVeggie.setForeground(new java.awt.Color(204, 0, 0));
        txtVeggie.setText("0");
        txtVeggie.setToolTipText("");
        txtVeggie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeggieActionPerformed(evt);
            }
        });

        lblVeggie.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblVeggie.setForeground(new java.awt.Color(0, 153, 255));
        lblVeggie.setText("Veggie Lovers Pizza ($9.99):");

        BtnCalculateCost.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnCalculateCost.setForeground(new java.awt.Color(255, 51, 51));
        BtnCalculateCost.setText("Calculate Cost");
        BtnCalculateCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalculateCostActionPerformed(evt);
            }
        });

        txtPepperoni.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtPepperoni.setForeground(new java.awt.Color(204, 0, 0));
        txtPepperoni.setText("0");
        txtPepperoni.setToolTipText("");
        txtPepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPepperoniActionPerformed(evt);
            }
        });

        lblPepperoni.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblPepperoni.setForeground(new java.awt.Color(0, 153, 255));
        lblPepperoni.setText("Pepperoni Pizza ($6.99):");

        txtCheese.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtCheese.setForeground(new java.awt.Color(204, 0, 0));
        txtCheese.setText("0");
        txtCheese.setToolTipText("");
        txtCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheeseActionPerformed(evt);
            }
        });

        lblCheese.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblCheese.setForeground(new java.awt.Color(0, 153, 255));
        lblCheese.setText("Cheese Pizza ($5.99):");

        txtPineapple.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtPineapple.setForeground(new java.awt.Color(204, 0, 0));
        txtPineapple.setText("0");
        txtPineapple.setToolTipText("");
        txtPineapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPineappleActionPerformed(evt);
            }
        });

        lblPineapple.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblPineapple.setForeground(new java.awt.Color(0, 153, 255));
        lblPineapple.setText("Pineapple Pizza ($7.99):");

        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pleasant Pizza's");

        picPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.jpg"))); // NOI18N

        Welcome1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Welcome1.setForeground(new java.awt.Color(51, 51, 255));
        Welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome1.setText("Welcome! Enter the number of each type of");

        Welcome2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Welcome2.setForeground(new java.awt.Color(51, 51, 255));
        Welcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome2.setText("pizza that you would like to buy and click calculate.");

        lblMeat.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblMeat.setForeground(new java.awt.Color(0, 153, 255));
        lblMeat.setText("Meat Lovers Pizza ($10.99):");

        txtMeat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtMeat.setForeground(new java.awt.Color(204, 0, 0));
        txtMeat.setText("0");
        txtMeat.setToolTipText("");
        txtMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeatActionPerformed(evt);
            }
        });

        lblOutput.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(0, 0, 0));
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTaxes.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTaxes.setForeground(new java.awt.Color(0, 153, 255));
        lblTaxes.setText("Taxes (13%):");

        lblSubtotal.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(0, 153, 255));
        lblSubtotal.setText("Subtotal:");

        lblTotal.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 153, 255));
        lblTotal.setText("Grand Total:");

        lblTotalOut.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTotalOut.setForeground(new java.awt.Color(204, 0, 0));
        lblTotalOut.setText("$0.00");

        lblSubtotalOut.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblSubtotalOut.setForeground(new java.awt.Color(204, 0, 0));
        lblSubtotalOut.setText("$0.00");

        lblTaxesOut.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTaxesOut.setForeground(new java.awt.Color(204, 0, 0));
        lblTaxesOut.setText("$0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Welcome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addComponent(picPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVeggie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVeggie, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCheese)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPepperoni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPepperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMeat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPineapple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPineapple, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTaxes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTaxesOut))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubtotalOut))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalOut))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCalculateCost)
                                .addGap(10, 10, 10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Welcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)
                        .addComponent(Welcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVeggie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVeggie)
                    .addComponent(BtnCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPepperoni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPepperoni))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheese)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaxes)
                            .addComponent(lblTaxesOut))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPineapple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPineapple))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSubtotal)
                        .addComponent(lblSubtotalOut)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMeat)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalOut))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(Welcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(302, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVeggieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeggieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeggieActionPerformed

    private void BtnCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalculateCostActionPerformed

        // Initializes and declares all the constants (the tax rate and the prices)
        // Initializes the tax, subtotal, and total
        final double TAX_RATE = 0.13;
        final double VEGGIE_PRICE = 9.99;
        final double PEP_PRICE = 6.99;
        final double CHEESE_PRICE = 5.99;
        final double PINE_PRICE = 7.99;
        final double MEAT_PRICE = 10.99;
        double tax;
        double subtotal;
        double total;

        // Gets the amount of each type of pizza entered and stores into a separate variable for each
        double veggieAmount = Double.parseDouble(txtVeggie.getText());
        double pepAmount = Double.parseDouble(txtPepperoni.getText());
        double cheeseAmount = Double.parseDouble(txtCheese.getText());
        double pineAmount = Double.parseDouble(txtPineapple.getText());
        double meatAmount = Double.parseDouble(txtMeat.getText());

        // Calculates the Subtotal and then rounds it to 2 decimal places
        // Stores in variables
        subtotal = (veggieAmount * VEGGIE_PRICE) + (pepAmount * PEP_PRICE) + (cheeseAmount * CHEESE_PRICE) + (pineAmount * PINE_PRICE) + (meatAmount * MEAT_PRICE);
        subtotal = (double) Math.round(subtotal * 100) / 100;

        // Calculates the tax (subtotal * tax rate) and then rounds it to 2 decimal places
        // Stores in variables
        tax = subtotal * TAX_RATE;
        tax = (double) Math.round(tax * 100) / 100;

        //Calculates total by adding subtotal and tax
        //Rounds it and stores in variables
        total = subtotal + tax;
        total = (double) Math.round(total * 100) / 100;

        //Outputs the required text (the costs) by setting the label text
        lblSubtotalOut.setText("$" + subtotal);
        lblTaxesOut.setText("$" + tax);
        lblTotalOut.setText("$" + total);

    }//GEN-LAST:event_BtnCalculateCostActionPerformed

    private void txtPepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPepperoniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPepperoniActionPerformed

    private void txtCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheeseActionPerformed

    private void txtPineappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPineappleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPineappleActionPerformed

    private void txtMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalculateCost;
    private javax.swing.JLabel Welcome1;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JLabel lblCheese;
    private javax.swing.JLabel lblMeat;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblPepperoni;
    private javax.swing.JLabel lblPineapple;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalOut;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblTaxesOut;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalOut;
    private javax.swing.JLabel lblVeggie;
    private javax.swing.JLabel picPizza;
    private javax.swing.JTextField txtCheese;
    private javax.swing.JTextField txtMeat;
    private javax.swing.JTextField txtPepperoni;
    private javax.swing.JTextField txtPineapple;
    private javax.swing.JTextField txtVeggie;
    // End of variables declaration//GEN-END:variables
}
