/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDiam = new javax.swing.JTextField();
        lblDiam = new javax.swing.JLabel();
        BtnCalculateCost = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        Welcome1 = new javax.swing.JLabel();
        Welcome2 = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalOut = new javax.swing.JLabel();
        lblSubtotalOut = new javax.swing.JLabel();
        lblTaxesOut = new javax.swing.JLabel();
        picPizza = new javax.swing.JLabel();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDiam.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtDiam.setForeground(new java.awt.Color(204, 0, 0));
        txtDiam.setText("0");
        txtDiam.setToolTipText("");
        txtDiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiamActionPerformed(evt);
            }
        });

        lblDiam.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblDiam.setForeground(new java.awt.Color(0, 153, 255));
        lblDiam.setText("Diameter of Pizza");

        BtnCalculateCost.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnCalculateCost.setForeground(new java.awt.Color(255, 51, 51));
        BtnCalculateCost.setText("Calculate Cost");
        BtnCalculateCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalculateCostActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Putrid Pizza's");

        Welcome1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Welcome1.setForeground(new java.awt.Color(51, 51, 255));
        Welcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome1.setText("Welcome! Enter the diameter of the pizza");

        Welcome2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Welcome2.setForeground(new java.awt.Color(51, 51, 255));
        Welcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome2.setText("that you would like to buy and click calculate.");

        lblTaxes.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTaxes.setForeground(new java.awt.Color(0, 153, 255));
        lblTaxes.setText("Taxes (13%):");

        lblSubtotal.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(0, 153, 255));
        lblSubtotal.setText("Subtotal:");

        lblTotal.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 153, 255));
        lblTotal.setText("Grand Total:");

        lblTotalOut.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTotalOut.setForeground(new java.awt.Color(204, 0, 0));
        lblTotalOut.setText("$0.00");

        lblSubtotalOut.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblSubtotalOut.setForeground(new java.awt.Color(204, 0, 0));
        lblSubtotalOut.setText("$0.00");

        lblTaxesOut.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        lblTaxesOut.setForeground(new java.awt.Color(204, 0, 0));
        lblTaxesOut.setText("$0.00");

        picPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Makingpizza.jpg"))); // NOI18N

        lblOutput.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(153, 0, 51));
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtnCalculateCost)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalOut))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSubtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubtotalOut))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTaxes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTaxesOut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(picPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Welcome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Welcome2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))))
                    .addComponent(lblOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Welcome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Welcome2))
                    .addComponent(picPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCalculateCost, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtotal)
                            .addComponent(lblSubtotalOut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaxes)
                            .addComponent(lblTaxesOut))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalOut))))
                .addGap(30, 30, 30)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiamActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDiamActionPerformed

    private void BtnCalculateCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalculateCostActionPerformed

        // Initializes and declares all the constants (the tax rate and the prices)
        // Initializes the tax, subtotal, and total
        final double TAX_RATE = 0.13;
        final double PER_DIAM_PRICE = 0.50;
        final double RENT_PRICE = 0.99;
        final double LABOUR_PRICE = 0.75;
        double tax;
        double subtotal;
        double total;

        // Gets the entered diameter and stores it into a variable
        double diameter = Double.parseDouble(txtDiam.getText());

        // Calculates the Subtotal and then rounds it to 2 decimal places
        // Stores in variables
        subtotal = (diameter * PER_DIAM_PRICE) + RENT_PRICE + LABOUR_PRICE;
        subtotal = (double) Math.round(subtotal * 100) / 100;

        // Calculates the tax (subtotal * tax rate) and then rounds it to 2 decimal places
        // Stores in variables
        tax = subtotal * TAX_RATE;
        tax = (double) Math.round(tax * 100) / 100;

        // Calculates total by adding subtotal and tax
        // Rounds it and stores in variables
        total = subtotal + tax;
        total = (double) Math.round(total * 100) / 100;

        // Based on the diameter, chooses to output different strings
        if ((diameter>=1)&&(diameter<=19)) {
            lblOutput.setText("We are going to make you a cute little pizza!");
        }
        else if ((diameter>=20)&&(diameter<40)) {
            lblOutput.setText("This will be delicious!");
        }
        else if (diameter>=40) {
            lblOutput.setText("Whoa, big pizza! You might need a truck to get this home!");
        }
        else {
            lblOutput.setText("Hey, why don't you want pizza? I'm still charging you!");
        }
        
        //Outputs the required text (the costs) by setting the label text
        lblSubtotalOut.setText("$" + subtotal);
        lblTaxesOut.setText("$" + tax);
        lblTotalOut.setText("$" + total);

    }//GEN-LAST:event_BtnCalculateCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalculateCost;
    private javax.swing.JLabel Welcome1;
    private javax.swing.JLabel Welcome2;
    private javax.swing.JLabel lblDiam;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalOut;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblTaxesOut;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalOut;
    private javax.swing.JLabel picPizza;
    private javax.swing.JTextField txtDiam;
    // End of variables declaration//GEN-END:variables
}
