/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ashish
 */
public class frmDiceGame extends javax.swing.JFrame {

    /**
     * Creates new form frmDiceGame
     */
    int totalRolls = 0;
    int totalCorrect = 0;
    int totalIncorrect = 0;
    int userGuess;
    int diceRoll;
    double percCorrect = 0;

    public frmDiceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblUserGuess = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        btnRollDice = new javax.swing.JButton();
        lblDiceRoll = new javax.swing.JLabel();
        lblRollValue = new javax.swing.JLabel();
        lblRolls = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 0, 204));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Super dice Guessing Game");

        lblInst1.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        lblInst1.setForeground(new java.awt.Color(0, 0, 204));
        lblInst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst1.setText("Enter a number, from 1 to 6");

        lblInst2.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        lblInst2.setForeground(new java.awt.Color(0, 0, 204));
        lblInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst2.setText("and click roll to roll the dice");

        lblUserGuess.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblUserGuess.setForeground(new java.awt.Color(0, 0, 204));
        lblUserGuess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserGuess.setText("Your Guess");

        txtUserGuess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUserGuess.setText("0");
        txtUserGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserGuessActionPerformed(evt);
            }
        });

        btnRollDice.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        btnRollDice.setForeground(new java.awt.Color(0, 0, 153));
        btnRollDice.setText("Roll Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        lblDiceRoll.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblDiceRoll.setForeground(new java.awt.Color(0, 0, 204));
        lblDiceRoll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiceRoll.setText("Dice Roll");

        lblRollValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRollValue.setText("0");

        lblRolls.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblRolls.setForeground(new java.awt.Color(0, 0, 204));
        lblRolls.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRolls.setText("Number Of Rolls:");

        lblIncorrect.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblIncorrect.setForeground(new java.awt.Color(0, 0, 204));
        lblIncorrect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIncorrect.setText("Number Of Incorrect Guesses:");

        lblPercent.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblPercent.setForeground(new java.awt.Color(0, 0, 204));
        lblPercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPercent.setText("Percentage Of Correct Guesses:");

        lblCorrect.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(0, 0, 204));
        lblCorrect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorrect.setText("Number Of Correct Guesses:");

        lblRollsValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRollsValue.setText("0");

        lblCorrectValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCorrectValue.setText("0");

        lblIncorrectValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIncorrectValue.setText("0");

        lblPercentValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPercentValue.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInst2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInst1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lblUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)
                                        .addComponent(lblRollValue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRolls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIncorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIncorrectValue, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addComponent(lblCorrectValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserGuess)
                    .addComponent(lblDiceRoll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRollValue))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRolls)
                    .addComponent(lblRollsValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrect)
                    .addComponent(lblCorrectValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncorrect)
                    .addComponent(lblIncorrectValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercent)
                    .addComponent(lblPercentValue))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserGuessActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        
        // selects a random integer from 1-6 and sets the text of the roll value
        diceRoll = (int) Math.round(Math.random() * 5 + 1);
        lblRollValue.setText(String.valueOf(diceRoll));

        //Gets the guess that the user inputed
        userGuess = Integer.parseInt(txtUserGuess.getText());

        // Adds one to the total rolls
        totalRolls = totalRolls + 1;

        // Check to see whether the guess the user inputed was equal to the random dice roll
        // Depending on that, it will add one to the correct or incorrect section
        if (diceRoll == userGuess) {
            totalCorrect = totalCorrect + 1;
        } else {
            totalIncorrect = totalIncorrect + 1;
        }

        // Calculates the percent of correct guesses
        percCorrect = ((double) totalCorrect / (double) totalRolls) * 100;

        // Rounds the percent of correct guesses
        percCorrect = (double) Math.round(percCorrect * 100) / 100;

        // Outputs / sets the text of the values
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percCorrect));

    }//GEN-LAST:event_btnRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblDiceRoll;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollValue;
    private javax.swing.JLabel lblRolls;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblUserGuess;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
